sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.4"
 
# command to install dependencies
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.6" ]]; then pip install -r requirements-2.6-dev.txt; else pip install -r requirements-dev.txt; fi

# command to run tests
script: nosetests tests/unit
